# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 04:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('address', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_day1.Company')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='工作内容如下')),
                ('order_address', models.CharField(default='岭澳一号机', max_length=64)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 12, 8, 4, 5, 2, 439415, tzinfo=utc))),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(default=datetime.datetime(2017, 12, 8, 4, 5, 2, 439415, tzinfo=utc))),
                ('status', models.IntegerField(choices=[(0, '编辑订单'), (1, '审核订单'), (2, '订单已审核'), (3, '允许工作'), (4, '工作中'), (5, '工作结束'), (6, '关闭订单')])),
                ('member', models.ManyToManyField(to='django_day1.Member')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(default='88888888', max_length=30)),
                ('create_time', models.DateField(default=datetime.datetime(2017, 12, 8, 4, 5, 2, 438415, tzinfo=utc))),
                ('last_login_time', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_day1.AccountRole')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_day1.Member')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_role', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='responsible_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_day1.UserAccount'),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_day1.WorkRole'),
        ),
    ]
