# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 04:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_day1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_day1.UserAccount'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 8, 4, 20, 16, 458694, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 8, 4, 20, 16, 458694, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2017, 12, 8, 4, 20, 16, 456694, tzinfo=utc)),
        ),
    ]
