# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 04:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_day1', '0002_auto_20171208_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='account',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 8, 4, 23, 9, 762606, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 8, 4, 23, 9, 762606, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2017, 12, 8, 4, 23, 9, 760606, tzinfo=utc)),
        ),
    ]
