# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 04:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_day1', '0003_auto_20171208_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='name',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 8, 4, 32, 22, 327211, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 8, 4, 32, 22, 327211, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2017, 12, 8, 4, 32, 22, 325211, tzinfo=utc)),
        ),
    ]
